### ISSUE TITLE
Incorrectly formatted text

### ISSUE THREAD

**Issue by bt4ibwem8** [blogdron/EPGTV#4]
On the first screenshot is displayed epg from your script and second screenshot is showing epg (from Iptvnator) correctly.
There is a little rectangle after each actor's name instead of the gap/space. Or even better if there would be comma + space.

<details>

<summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/4ad9c28f-1128-4dba-a32b-177f852c3768)

![image](https://github.com/user-attachments/assets/12cb1de0-24cc-4761-bdc2-7af2396b3d75)

</details>

**Comment by blogdron** [comment]
Can you share a link to the EPG data or a cache file?

cache location in linux `/home/$USER/.cache/EPGTV`
cache location in windows `C:\Users\user\AppData\Local\EPGTV`

paste it in https://gist.github.com/ in whole or in part which contains this text

It might just be a problem with your font in mpv , if so there's nothing I can do about it.

**Comment by bt4ibwem8** [comment]
[Here](http://m3u4u.com/xml/w16vy5k4q5hxdmwjy39p) you go...
The main problem is the actors are taking too much space (one actor per one line). So there is too much empty unused space on the screen.

**Comment by blogdron** [comment]
@bt4ibwem8,

 fixed, update and check :)

**Comment by bt4ibwem8** [comment]
cheers mate, now it runs correctly (i just tested it now in the new 0.39.0 mpv version)

**Comment by bt4ibwem8** [comment]
cheers mate, now it runs correctly (i just tested it now in the new 0.39.0 mpv version)

**Comment by bt4ibwem8** [comment]
It is incorrect again. [Here](http://m3u4u.com/xml/782dyqkg5xh1rz4qy4zp) is xml epg.

![image](https://github.com/user-attachments/assets/ed25df87-6a16-46d0-8e71-215cb4e1fdf4)

**Comment by blogdron** [comment]
@bt4ibwem8 this is strange, try update `EPG` script maybe, try press 'u' and update old tv cache

Im manual  prepare and check this tv info as title view and as next view. And no have new lines in screen
![img](https://i.ibb.co/z71Q7F7/2024-10-05-01-36-29.png)

And EPGCACHE okey, just one line
```
TEST "#" 202410050122 202410050522 3 "DOKTOR MARTIN" "Humorný seriál z prostredia podhorského mestečka Protějov v Beskydách. Stret svojráznej povahy nového obvodného lekára z Prahy s podhorským spôsobom života prinesie rad humorných, aj menej veselých, nečakaných situácií Petr Zahrádka Miroslav Donutil Jitka Čvančarová Gabriela Marcinková Jana Štěpánková Norbert Lichý Václav Kopta Tomáš Měcháček Tomáš Jeřábek Emília Vášáryová."
```

I can't confirm the problem.
Perhaps you have several directories with different configurations, or several players with different configurations and one of them contains an old EPGTV script

**Comment by bt4ibwem8** [comment]
You are right. Just updated epg data with `U` and now it is showing correctly. I am on the latest 0.39.0 mpv release version.
