### ISSUE TITLE
Add more options in conf.lua

### ISSUE THREAD

**Issue by bt4ibwem8** [blogdron/EPGTV#5]
Some suggestions:

- [x] `brakets=false`  -- disable the brakets around the times
- [x] `progress_percentages=false`  -- hide % of the progress of currently playing item
- [ ] scrolling around the text with UP/DOWN keys - maybe this could be implemented (in main.lua) in the new 0.39.0 mpv version because i see the scrolling is now possible on osd text for the stats pages (i)

**Comment by blogdron** [comment]
No have time now. Maybe latter 

* № 1 - Ok
* № 2 - Ok 
* № 3 - No (There are reasons for this. The current scrolling is a hack. To implement full-fledged scrolling, everything needs to be redone )

**Comment by blogdron** [comment]
@bt4ibwem8 update and check
```lua
   --------------------------
   --    visual brakets    --
   --------------------------
   brakets = true,            -- on/off brakets for clock and percent progress
   --------------------------
   --  progress percents   --
   --------------------------
   progress_percentages=true, -- on/off percent or progress in top title
```

**Comment by bt4ibwem8** [comment]
nice, it is now more polished
