### ISSUE TITLE
More consistency

### ISSUE THREAD

**Issue by bt4ibwem8** [blogdron/EPGTV#7]
It is just detail but it would look nicer if the time and the currently playing title would be in same order like further titles/programs. So first would be the time followed by the name of title...

**Comment by blogdron** [comment]
I'll think about it

**Comment by blogdron** [comment]
No, the time before the title of the current TV show spoils the look, considering that the font is large, it does not look consistent

If the text size of the current program was the same as the text size of the other programs, it would look good. But considering the difference in font sizes, it does not work.

**Comment by bt4ibwem8** [comment]
But in the following programmes are font sizes also different and it looks fine imo. Could you post some screenshot here please? So i could see what it looks like...

**Comment by blogdron** [comment]
My previos implementation looks bad,  Im try make other visual 

Without percentage

![img](https://i.ibb.co/CP4KLnJ/2024-12-18-14-13-59.png)

With percentage

![img](https://i.ibb.co/3R9bB49/2024-12-18-14-18-26.png)

Maybe  this okey? 

Or maybe this 

![img](https://i.ibb.co/HDyyrw4/2024-12-18-14-26-22.png)


Or maybe use all variants and select in config, `top_title_style=1 -- 1 or 2 or 3`

**Comment by blogdron** [comment]
@bt4ibwem8  Hello, Im no have time for wait answer, and not have time in future for discussion about it. Since I have a lot of things to do, but I don’t want to leave everything here unanswered for a long time again, so I decided to do it right away.=)
  Now you can in configuration set another style for top title

```lua

   --------------------------
   --   playinfo style     --
   --------------------------
   top_title_playinfo_style=1, -- 1 -- time + percent in right (default)
                               -- 2 -- time + percent in left 
                               -- 3 -- time + percent under top title 

```

Set this in you `conf.lua` and update script. 

Closed now, because resolved :)

Resolved?

-----

I hope, this not add bugs...

**Comment by bt4ibwem8** [comment]
hi, could you please implement first one? i have percentage and brackets removed. So it would look like this, just swapped:

![image](https://github.com/user-attachments/assets/7699e799-203b-4783-a5de-41fd756abd03)

**Comment by blogdron** [comment]
@bt4ibwem8 Done. Update `EPGTV` and set in config file `top_title_playinfo_style=2`

**Comment by blogdron** [comment]
![img](https://i.ibb.co/0G1jf94/2024-12-18-19-44-56.png)

```lua
   --------------------------
   --    visual brakets    --
   --------------------------
   brakets = false,            -- on/off brakets for clock and percent progress
   --------------------------
   --  progress percents   --
   --------------------------
   progress_percentages=false, -- on/off percent or progress in top title
   --------------------------
   --   playinfo style     --
   --------------------------
   top_title_playinfo_style=2, -- 1 -- time + percent in right
                               -- 2 -- time + percent in left
                               -- 3 -- time + percent under top title
```

**Comment by bt4ibwem8** [comment]
It does not work for me in Windows. No epg data are displayed. Did you update script? Because i see last update 7 hours ago...

**Comment by blogdron** [comment]
@bt4ibwem8  yes, script updated, but Im make changes only for format, and Im tested, all works on Linux, Im dont touch any other logic. I do not known,  maybe you need update you EPG data. All the script logic remains unchanged, and everything should continue to work as it did before. 

https://github.com/blogdron/EPGTV/commit/083d5b72c673aa446ef47b18806ccb33a7bf5444

**Comment by bt4ibwem8** [comment]
Sorry, my fault. I forgot to put `,` at the end of line. Now it works well:

![image](https://github.com/user-attachments/assets/1c65a468-fa41-4b17-8896-9ba68df06bf1)
